### ISSUE TITLE
Generate table from array of structs

### ISSUE THREAD

**Issue by hutou** [matt-harvey/tabulo#1]
Hi,
I  just want to make a table from an array of structs.
Here is an example : 

```
require 'tabulo'

Pdata = Struct.new(:name, :age)

persons = []
persons << Pdata.new("Joe", 45)
persons << Pdata.new("Sam", 33)
persons << Pdata.new("Harvey", 72)
persons << Pdata.new("Jimmy", 14)

puts persons.class
puts persons

table = Tabulo::Table.new(???) do |t|
    t.add_column("Name", ???)
    t.add_column("Age", ???)
end

puts table
```
How can I do that ?
Thanks for your help.

**Comment by matt-harvey** [comment]
Hey.

```
table = Tabulo::Table.new(persons, columns: %[name age])
puts table
```

will output

```
+--------------+--------------+
|     name     |      age     |
+--------------+--------------+
| Joe          |           45 |
| Sam          |           33 |
| Harvey       |           72 |
| Jimmy        |           14 |
```

If it's important that the column names be capitalized, then you can achieve that as follows:

```
table = Tabulo::Table.new(persons) do |t|
  t.add_column("Name", &:name)
  t.add_column("Age", &:age)
end

puts table
```

This will output

```
+--------------+--------------+
|     Name     |      Age     |
+--------------+--------------+
| Joe          |           45 |
| Sam          |           33 |
| Harvey       |           72 |
| Jimmy        |           14 |
```

**Comment by hutou** [comment]
Thanks a lot for your answer.
I just managed to make the gem work. Here is what I did 
```
table = Tabulo::Table.new(persons) do |t|
    t.add_column("Name\nsurname", &:name)
    t.add_column("\nAge", &:age)
    t.add_column("Age2", width:4, &:age)
    t.add_column("Age3", width:5, formatter: -> (n) {"%.2f" % n }) do |n| n.age * 2 / 3.0 end
end
```
which gives
```
+--------------+--------------+------+-------+
|     Name     |              | Age2 |  Age3 |
|    surname   |      Age     |      |       |
+--------------+--------------+------+-------+
| Joe          |           45 |   45 | 30.00 |
| Sam          |           33 |   33 | 22.00 |
| Harvey       |           72 |   72 | 48.00 |
| Jimmy        |           14 |   14 |  9.33 |
```
Your gem looks very powerful.
Not found yet how to output a closing line of dashes, but I continue to experiment...
Thanks again.

**Comment by matt-harvey** [comment]
For the closing line of dashes, try

`puts table.horizontal_rule`

Or to print in one go with the table:

`puts "#{table}\n#{table.horizontal_rule}"`

See http://www.rubydoc.info/gems/tabulo/Tabulo%2FTable:horizontal_rule

No probs.

**Comment by hutou** [comment]
Awesome !
Thanks for the link.

**Comment by hutou** [comment]
A last(?) question : is it possible to remove vertical column separators to obtain something like 
```
-----------------------------------------
     Name                    Age2   Age3 
    surname         Age                  
-----------------------------------------
 Joe                     45    45  30.00 
 Sam                     33    33  22.00 
 Harvey                  72    72  48.00 
 Jimmy                   14    14   9.33
```

**Comment by matt-harvey** [comment]
That behaviour is not "officially" supported, however you can approximate it in a hacky way as follows:

```
Tabulo::Table::VERTICAL_RULE_CHARACTER = " "
Tabulo::Table::CORNER_CHARACTER = "-"
# Then initialize and print your table as before...
```

Ruby will warn you about an "already initialized constant"; just ignore that.

This won't remove the vertical separator as such, but it will make it so that a space is used _as_ the vertical separator. So relative to your desired endpoint as shown above, there will be one extra space between the columns.

If you're keen for this feature to be officially supported (with proper options for configuring it when initializing the table), please create a separate Issue in GitHub, labelled as a Feature request (although I can't make any promises about when I will implement it). PRs are also welcome :)
