### ISSUE TITLE
Colored output via rainbow

### ISSUE THREAD

**Issue by leoc** [matt-harvey/tabulo#11]
Heyya! First let me express my gratitude! Very nice gem and very nice documentation. :+1: 

I am having only a little issue. I am using [sickill/rainbow](https://github.com/sickill/rainbow) to colorize my output. For instance to highlight certain values or rows. Unfortunately the table gets scrambled, maybe because tabulo does not take the special characters into account, that are not displayed.

I don't know yet how to solve this most elegantly. Maybe just removing all /\\e\[[^m]+?m/ when accessing the length of the string.

![2021-03-06-093108_1903x471_scrot](https://user-images.githubusercontent.com/184696/110200553-d75aa680-7e5e-11eb-945e-e7cf32b91762.png)

Edit: I just found out, that we need to do more I think, when tabulo wraps long headings oder cell data for instance the color goes til the end of the cell data string spanning multiple lines, causing the table border to be of the wrong color.

So I think we have to reset the terminal color explicitly.

![](https://media3.giphy.com/media/10IjYHN26w8Zg7XFtU/giphy.gif)

Have a beautiful weekend!

**Comment by leoc** [comment]
Oh my, you thought of everything. I will try the styler options!

**Comment by matt-harvey** [comment]
:+1: :slightly_smiling_face:
