### ISSUE TITLE
Skip a row but keep headers

### ISSUE THREAD

**Issue by ineu** [matt-harvey/tabulo#16]
First of all, thank you for the great library.

I'm trying to print rows conditionally. To achieve this, I'm using `table.each` with `next`. The snippet follows.

Actual behavior: The problem is that headers seem to be tied to the first row. If the row is skipped, so are the headers.
Expected behavior: The headers should be shown regardless of the rows.

Code:
```ruby
#!/usr/bin/env ruby

require 'tabulo'

table = Tabulo::Table.new([['one', true], ['two', false]], :first, :last)

puts "Without headers"
table.each do |row|
  next if row.source.last
  puts row
end

puts "With headers"
table.each do |row|
  next if !row.source.last
  puts row
end
```

Output:
```
Without headers
| two          |     false    |
With headers
+--------------+--------------+
|     first    |     last     |
+--------------+--------------+
| one          |     true     |
```

**Comment by matt-harvey** [comment]
Hi @ineu , thanks for using Tabulo!

You should be able to achieve your desired outcome, in at least one of a couple of ways.

### Way 1: Filtering your data before initializing the table

The simplest way may be to filter your input data before tabulating it. So in this example, that would look something like this:

```rb
data = [['one', true], ['two', false]]
filtered_data = data.select(&:last)
puts Tabulo::Table.new(filtered_data, :first, :last)
```

### Way 2: Low level control of table rendering

If Way 1 isn't feasible for whatever reason, then you can also achieve the same outcome using some low level methods on `Tabulo::Table`. The documentation for these is perhaps a little obscure, but here they are:
* [`#formatted_header`](https://www.rubydoc.info/gems/tabulo/Tabulo%2FTable:formatted_header): This allows you to print just the header row in isolation (without the horizontal borders above and below, and without being "attached" to any of the body rows)
* [`#horizontal_rule`](https://www.rubydoc.info/gems/tabulo/Tabulo/Table#horizontal_rule-instance_method): This allows you to print the horizontal borders in isolation.

In addition, the `header_frequency:` option of the `Tabulo::Table` [initializer](https://www.rubydoc.info/gems/tabulo/Tabulo%2FTable:initialize) allows you to switch off automatic header printing, by passing `nil` to that option.

The complete solution using this strategy, would look like the following, using your example:

```rb
table = Tabulo::Table.new([['one', true], ['two', false]], :first, :last, header_frequency: nil)

# "Manually" print the header
puts table.horizontal_rule(:top)
puts table.formatted_header
puts table.horizontal_rule(:middle)

# Print the table body as before
table.each do |row|
  next if row.source.last
  puts row
end

# Manually print the bottom border (if you want)
puts table.horizontal_rule(:bottom)
```

Let me know how you go :)

**Comment by ineu** [comment]
Option 1 is not really suitable for my use case: I have a pretty slow process that prints table in a streaming way. I believe 2 is what I was looking for, thank you.

I used a third option: lazy filtering of the dataset. This removed `next` from the loop, printing the first line with headers. Something like:
```ruby
data = local_bp_orders.map { |x| OrderWrapper.new(x) }.lazy.select { |x| x.amount_differs? }
table = Tabulo::Table.new(data, border: :blank)
# ... a bunch of add_column
table.each do |row|
  puts row
end
```

**Comment by matt-harvey** [comment]
Glad you got it working @ineu . And nice solution using `lazy` to tabulate streaming data 👍
