### ISSUE TITLE
Allow finer grained control of the resizings currently done by `.pack`

### ISSUE THREAD

**Issue by matt-harvey** [matt-harvey/tabulo#22]
Following the discussion in https://github.com/matt-harvey/tabulo/issues/18, it seems it will be useful to allow users to have greater control over the action of `Tabulo::Table#pack`. The `.pack` method really does three different things:
1. Autosizes columns to fit their contents
2. Potentially shrinks columns as required for the table as a whole to fit the passed `max_table_width:` (or the terminal width if passed the default `:auto`)
3. Potentially expands columns as required to accommodate a long title

Step 3 is buggy in that it can override the `max_table_width`. This is covered separately in https://github.com/matt-harvey/tabulo/issues/20. Step 3 should be ignored for the purposes of the present Issue.

For the present Issue, what we want is for the user to be able to enact 1 and 2 individually, and to modulate the action of these separately by passing an `:except` argument that could exclude certain columns from their action.

For example, the user should be able to do this:

```rb
table.autosize_columns.shrink_to(:screen, except: :id)
```

This would express that they want all columns to be just wide enough to accommodate their contents, but then have the table shrunk to be just wide enough for the screen width, with columns shrunk as required to permit this _except for_ the `:id` column, which should never be shrunk. In other words, it would enable them to exclude the `:id` column from the shrinking-to-screen action, _without_ excluding it from the autosize-to-contents action. This is something that is not possible using the `except:` parameter on `pack` that is currently implemented on the `v2-8` branch.

**Comment by matt-harvey** [comment]
I have now implemented this on the [v2-8](https://github.com/matt-harvey/tabulo/tree/v2-8).

@jaynetics FYI, once these changes are released, you will be able to do this:

```rb
table.autosize_columns.shrink_to(:screen, except: :id)
```

This should provide a nicer solution to https://github.com/matt-harvey/tabulo/issues/18, avoiding the need to precalculate the column width for `:id` within the client code.

I'll leave this for a couple of days or so, to leave time in case you or others have any feedback on this proposed solution&mdash;or in case I think of any downsides to this myself. If nothing comes up, then I'll cut a v2.8.0 release in the next few days, that incorporates these changes.

**Comment by matt-harvey** [comment]
Implemented in `v2.8.0` release.

**Comment by jaynetics** [comment]
@matt-harvey thank you very much for the extended solution and thorough communication! this worked perfectly for my use case and i've just released a new version of my gem. i think you came up with the most clean and maintainable approach, and i hope others will find it useful as well. if you ever feel like you want a second opinion on future developments, feel free to ping me.

**Comment by matt-harvey** [comment]
No worries @jaynetics. Thanks for your contributions as well. I'm happy to hear that the changes have worked well for your gem.

>  if you ever feel like you want a second opinion on future developments, feel free to ping me.

Thank you. I'm sure I will find this helpful in future 😃
